### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by IMFsy** [parallelcc/MiCTS#1]
按使用说明设置好之后 长按白条后屏幕四周闪一秒白圈，就没有反应了
谷歌版本 15.42.35.28.arm64 (301414170)
桌面版本 RELEASE-4.39.14.8255-09101541 (439148255)

**Comment by parallelcc** [comment]
提供一下手机型号和系统版本，尝试将Google的自启动权限打开，省电策略选择无限制

**Comment by IMFsy** [comment]
> 提供一下手机型号和系统版本，尝试将Google的自启动权限打开，省电策略选择无限制

Redmi K50 安卓14 hyper1.0.12 自启动已打开 无限制已打开

**Comment by parallelcc** [comment]
Google可以正常手动打开吗

**Comment by IMFsy** [comment]
> Google可以正常手动打开吗

现在可以了  清楚谷歌数据后重新打开就可以使用了。哈哈麻烦了。
