### ISSUE TITLE
Can't triggered by the navigation handle on Tablet (PAD)

### ISSUE THREAD

**Issue by Mustafarexdo** [parallelcc/MiCTS#10]
The circle to search doesn't work as expected when using gestures (navigation handle) on a tablet, although it works fine with buttons. It seems like the gestures are not being recognized or processed correctly on tablet devices. Could you please look into this.

Can it be triggered by the navigation handle : **NO**

Can it be triggered by the home button : **Yes**

Device model: MI PAD 5

OS version : **hyperOS 2.0.1.10**

Android version : **15**

Launcher version : **4.41.19.8328-10181619**

**Comment by parallelcc** [comment]
Since I don't have a tablet, it's hard to troubleshoot. But there is a workaround: try [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)

Launching the app will trigger so you can customize the trigger with other apps/modules like xposed edge
