### ISSUE TITLE
Question || Possible LSPatch support for Xiaomi trigger? 

### ISSUE THREAD

**Issue by mint1246** [parallelcc/MiCTS#12]
Sorry if this is a waste of time, but I wondered if it was possible to use LSPatch to trigger it on Xiaomi devices automatically, I noticed the min version of xposed is 100, where lspatch ends at 93. It doesn't show up as a module so I couldn't test it, i tried building it with min version set to 93 (not sure if thats the only reason it doesnt show up as a module in Patch) but I quickly realized i'm not a dev & chatgpt could only get me so far & that i have no idea how to build myself.

**Comment by parallelcc** [comment]
The Xiaomi triggers in the module rely on the System Framework and System Launcher, so even if you can use lspatch to build patched versions, you can't replace them from the system without root

**Comment by Qwertdery** [comment]
> Sorry if this is a waste of time, but I wondered if it was possible to use LSPatch to trigger it on Xiaomi devices automatically, I noticed the min version of xposed is 100, where lspatch ends at 93. It doesn't show up as a module so I couldn't test it, i tried building it with min version set to 93 (not sure if thats the only reason it doesnt show up as a module in Patch) but I quickly realized i'm not a dev & chatgpt could only get me so far & that i have no idea how to build myself.

The thing is that for the gesture navigation part , can be done without rooting your phone. there might be apps that do the job like pressing the gesture handle does an action ( with a workaround of course!) but for the normal navigation bar? probably the same. (I'd assume that could work with some workaround i don't even know)
