### ISSUE TITLE
Upper part of the screen not working when CTS triggered

### ISSUE THREAD

**Issue by ASB101** [parallelcc/MiCTS#13]
https://github.com/user-attachments/assets/3daf4162-7f1c-4dee-a952-4bb94ad2ab34

**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**

**屏幕边缘是否闪了 / Did the screen edge flash?**

**是否可以通过其他方式触发 / Can it be triggered by other methods?**

**设备型号 / Device model**

**系统版本 / OS version**

**Android 版本 / Android version**

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed

**Comment by ASB101** [comment]
My device is redmi note 10 pro, It does work even the top when force stoping the google app, changing device to p7 pro or 8 didn't change anything..

**Comment by parallelcc** [comment]
This is just a trigger, so it cannot address the compatibility issues of Circle to Search itself. I can only suggest clearing Google's data or spoofing a device model similar to yours to see if that helps.
