### ISSUE TITLE
[QUESTION] How do I make it run on long home button press?

### ISSUE THREAD

**Issue by neoapps-dev** [parallelcc/MiCTS#16]
How do I make it run on long press for home button,

Devices I wanna do it in:

- Redmi 12 (Android 14): the app works perfectly, but i cant set it to run on home button long press

- Infinix HOT 30 (Android 13): the app works perfectly, but i cant set it to run on home button long press

- Realme 11 (Android 14): the app works perfectly, but i cant set it to run on home button long press

thanks.

**Comment by parallelcc** [comment]
Only Xiaomi devices can enable `Trigger by long press home button` in Module Settings after activating the module in LSPosed (root required)

see `3. Set up the trigger method` in [How to Use](https://github.com/parallelcc/MiCTS/blob/main/README_en.md#how-to-use)
