### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by sariyan-0** [parallelcc/MiCTS#17]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used
No

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**
![Screenshot_20241201_183347_MiCTS](https://github.com/user-attachments/assets/910f4429-25ba-4c73-8d58-c9aa10b45dab)

**屏幕边缘是否闪了 / Did the screen edge flash?**
No

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
No

**设备型号 / Device model**
A52 5G

**系统版本 / OS version**
One UI 6

**Android 版本 / Android version**
Android 14

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed

**Comment by parallelcc** [comment]
It's not guaranteed to work on every device **without root**, as Google does do some device checks

You can check the logcat for the message `Omni invocation failed: not enabled` to confirm whether the checks were not passing

**Comment by parallelcc** [comment]
> ![Screenshot_20241202-195800](https://private-user-images.githubusercontent.com/161915364/391581818-c2e0f650-29b8-4f85-a64b-dbca000095e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTAzMTgsIm5iZiI6MTczMzE1MDAxOCwicGF0aCI6Ii8xNjE5MTUzNjQvMzkxNTgxODE4LWMyZTBmNjUwLTI5YjgtNGY4NS1hNjRiLWRiY2EwMDAwOTVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxNDMzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTY1NzFjMGU2ZmY2YmYwNWZiZjRmMmYyNjc5YWNiYmMyMTNiNTFlOTk3NGIwNmUwNjA0ZGQ0NDcyZTI5ZmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.09k5wgxLHQVrioyfJ-EZgMQuFAoNRGOhtmO157KGALg)
> 
> > You can check the logcat for the message `Omni invocation failed: not enabled` to confirm whether the checks were not passing
> 
> that's it?

Yes, `enableOmnient=false` means your device is disabled to use Circle to Search due to Google's flag, you need to root to bypass the check

**Comment by baianohak** [comment]
Can you tell me what specific version of the Google app this is?
