### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hoangquiqui** [parallelcc/MiCTS#18]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
•Confirm Google is enabled and no app modes are restricted 
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used
Confirm Google is enabled and no app modes are restricted

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**

![IMG_1733094557308_1733094559701](https://github.com/user-attachments/assets/04727492-0a0f-40a3-b05c-4891e56840fe)
![Screenshot_2024-12-02-06-09-24-638_com parallelc micts](https://github.com/user-attachments/assets/a241814b-a77f-4222-aed6-554a980a8409)

**屏幕边缘是否闪了 / Did the screen edge flash?**
No

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
I have tried activating it in many ways, inserting a virtual key, inserting a button on the side, inserting it into the phone status bar, pressing directly, the phenomenon occurs. But an error occurs as shown in the photo.

**设备型号 / Device model**
Redmi note 12 turbo

**系统版本 / OS version**
1.0.9.0 ( hyper os)
**Android 版本 / Android version**

Android 14
**桌面版本（小米设备） / Launcher version (Xiaomi devices)**
Yes xiaomi

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
Sorry I'm new I don't understand this problem please help me in an easy to understand way What a great app LSPosed is
> Upload the zip file exported by the save button at the top of the log tab in LSPosed
Sorry I'm new I don't understand this problem please help me in an easy to understand way What a great app LSPosed is

**Comment by Hoangquiqui** [comment]
Looks like I know how to fix the error, I rarely use the navigation bar, when I turn them off, turning on mcts won't work. When I turn on the navigation bar, it will work.

**Comment by parallelcc** [comment]
> Looks like I know how to fix the error, I rarely use the navigation bar, when I turn them off, turning on mcts won't work. When I turn on the navigation bar, it will work.

Do you mean the buttons or the small white bar for the gestures? Ensure Google is selected in `Settings - Apps - Manage apps - Other Settings in the upper right corner - Default apps - Assist & voice input - Digital Assistant App` and check if you can open Google Assistant by swiping from the corner or long pressing the Home button

**Comment by Duc-python** [comment]
> > Looks like I know how to fix the error, I rarely use the navigation bar, when I turn them off, turning on mcts won't work. When I turn on the navigation bar, it will work.
> 
> Do you mean the buttons or the small white bar for the gestures? Ensure Google is selected in `Settings - Apps - Manage apps - Other Settings in the upper right corner - Default apps - Assist & voice input - Digital Assistant App` and check if you can open Google Assistant by swiping from the corner or long pressing the Home button

I don't see Default apps - Assist & voice input - Digital Assistant App

**Comment by parallelcc** [comment]
> > > Looks like I know how to fix the error, I rarely use the navigation bar, when I turn them off, turning on mcts won't work. When I turn on the navigation bar, it will work.
> > 
> > 
> > Do you mean the buttons or the small white bar for the gestures? Ensure Google is selected in `Settings - Apps - Manage apps - Other Settings in the upper right corner - Default apps - Assist & voice input - Digital Assistant App` and check if you can open Google Assistant by swiping from the corner or long pressing the Home button
> 
> I don't see Default apps - Assist & voice input - Digital Assistant App

Xiaomi device?
