### ISSUE TITLE
Open MiCTS on handle bar hold

### ISSUE THREAD

**Issue by PadowYT2** [parallelcc/MiCTS#19]
:wave:, I have a Poco X5 5G (which is Xiaomi) with crDroid (a custom rom) which is rooted. Holding the handle bar, does nothing at all

**Comment by parallelcc** [comment]
Only supports stock roms for Xiaomi devices

**Comment by PadowYT2** [comment]
> Only supports stock roms for Xiaomi devices

I see, thanks, are there any other methods to activate MiCTS via the handle bar?

**Comment by parallelcc** [comment]
> > Only supports stock roms for Xiaomi devices
> 
> I see, thanks, are there any other methods to activate MiCTS via the handle bar?

Try Xposed Edge, see https://github.com/parallelcc/MiCTS/issues/9#issuecomment-2470088043
