### ISSUE TITLE
小米的提示线触发范围太小

### ISSUE THREAD

**Issue by xzm25** [parallelcc/MiCTS#2]
多数情况识别为滑动，识别不出常按

**Comment by parallelcc** [comment]
试一下[1.2](https://github.com/parallelcc/MiCTS/releases/tag/v1.2)

**Comment by parallelcc** [comment]
之后的版本会提供一个触发入口，到时候可以通过其他软件，比如Xposed Edge自定义触发方式，那样就不依赖提示线了
