### ISSUE TITLE
don't open

### ISSUE THREAD

**Issue by mdsssa** [parallelcc/MiCTS#20]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**

**屏幕边缘是否闪了 / Did the screen edge flash?**
Yes

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
No

**设备型号 / Device model**
Nothing phone (1) a063

**系统版本 / OS version**
nothing os 2.6

**Android 版本 / Android version**
14

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed

**Comment by parallelcc** [comment]
See https://github.com/parallelcc/MiCTS/issues/17#issuecomment-2509815143
