### ISSUE TITLE
The screen is flashing but the Google search bar doesn't come up

### ISSUE THREAD

**Issue by techoprek** [parallelcc/MiCTS#21]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used
 
Yes, Done

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**

https://github.com/user-attachments/assets/18ffc4da-7277-451d-b7d2-23843ef5fc9c

**屏幕边缘是否闪了 / Did the screen edge flash?**

Yes

**是否可以通过其他方式触发 / Can it be triggered by other methods?**

Maybe no

**设备型号 / Device model**

ADVAN Tab Sketsa 3

**系统版本 / OS version**

(Stock Android)

**Android 版本 / Android version**

13

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed

This tablet bootloader is still locked

**Comment by parallelcc** [comment]
See https://github.com/parallelcc/MiCTS/issues/17#issuecomment-2509815143

**Comment by techoprek** [comment]
How to set `enableOmnient` to true?

**Comment by parallelcc** [comment]
> How to set `enableOmnient` to `true` and `Omni invocation failed` to `enabled` ?

Need root
If `enableOmnient` is default, then just enable `Device spoof for Google` in MiCTS's Module Settings
If `enableOmnient` is false, then change `com.google.android.apps.search.omnient.device` flag `45631784` to true using [GMS-Flags](https://github.com/polodarb/GMS-Flags)

**Comment by kiber-io** [comment]
I have a root, but the specified flag is not in GMS Flags. I put it up, but the problem didn't go away, and it doesn't seem to be related to the checks at all. There is a pattern:
1. We are trying to call CTS - successfully.
3. We close it, try to call it again - everything is past, it does not work.
4. 3. Minimize the current application, go back and go to step 1, everything works again, but only once
