### ISSUE TITLE
通过磁贴触发圈定即搜，无法自动收起控制中心

### ISSUE THREAD

**Issue by hou9999** [parallelcc/MiCTS#22]
**问题描述 / Describe the bug**
如图所示，点按“圈定即搜”磁贴后控制面板不会自动收起
![Screenshot_20241210-095400](https://github.com/user-attachments/assets/96f3ec53-d86c-43ec-9c59-c97e9d34ea61)

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**
![Screenshot_20241210-095125](https://github.com/user-attachments/assets/e27b15b7-4a31-43f5-9eb2-ede2bd815e71)

**屏幕边缘是否闪了 / Did the screen edge flash?**
否

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
否

**设备型号 / Device model**
小米12spro

**系统版本 / OS version**
PixelOS 
AP2A.240905.003

**Android 版本 / Android version**
14

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**
pixel launcher

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed
[LSPosed_2024-12-10T10_08_05.802672.zip](https://github.com/user-attachments/files/18070483/LSPosed_2024-12-10T10_08_05.802672.zip)

**Comment by parallelcc** [comment]
用Pixel 5 A14测试了一下，是可以收起的，只是触发延迟可能得加大一点

如果加大触发延迟没有效果的话，那应该是rom的问题

**Comment by parallelcc** [comment]
Pixel 7 A15测试也没有问题

**Comment by hou9999** [comment]
好的，解决了，延迟加到1400ms就好了
