### ISSUE TITLE
CTS 在长按导航条后没有显示，HyperOS 2

### ISSUE THREAD

**Issue by rponeawa** [parallelcc/MiCTS#23]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used

我已将 Google 设置为默认助理应用，且没有限制后台。
在 HyperOS 2 上，当前台 app 不是系统桌面时，长按导航条会造成一个切换 app 的动画，但 CTS 页面并没有显示。而这种情况下，使用磁贴可正常调出 CTS；使用启动 MiCTS 的方法始终是工作的。

https://github.com/user-attachments/assets/dcee34d9-8b3d-4950-a04f-2614e9b5d1fb

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**
![Screenshot_2024-12-14-00-09-13-998_com parallelc micts](https://github.com/user-attachments/assets/966da88e-625f-4900-9d27-09ef9f3af7d9)

**屏幕边缘是否闪了 / Did the screen edge flash?**
在首次启动 MiCTS 时是的，后续没有。

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
是的。

**设备型号 / Device model**
Xiaomi 12S (mayfly)

**系统版本 / OS version**
2.0.26.8

**Android 版本 / Android version**
15

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**
RELEASE-5.39.31.10371-12062254

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed

[LSPosed_2024-12-14T00_17_02.715043.zip](https://github.com/user-attachments/files/18128705/LSPosed_2024-12-14T00_17_02.715043.zip)

**Comment by kiber-io** [comment]
There is a pattern:
1. We are trying to call CTS - successfully.
3. We close it, try to call it again - everything is past, it does not work.
4. Minimize the current application, go back and go to step 1, everything works again, but only once

Android 15, HyperOS 2

https://github.com/user-attachments/assets/f7c4b418-df3e-41d0-bfc1-23985b85c6dc

**Comment by parallelcc** [comment]
> There is a pattern:
> 
> 1. We are trying to call CTS - successfully.
> 2. We close it, try to call it again - everything is past, it does not work.
> 3. Minimize the current application, go back and go to step 1, everything works again, but only once
> 
> Android 15, HyperOS 2.
> 
> I added the 45631784 flag to GMS Flags (it wasn't there), but it didn't change anything.
> 
> This is relevant for CSService. When using CSHelper, the screen also flashes, but after flashing, the CTS still opens every time you try. When using VIS, the default assistant just opens (it's not Google for me). On Android 14, everything worked fine in the same configuration.
> 
> UPD. It also stopped working with CShelper 0_0
> 
>  Screenrecorder-2024-12-13-23-53-28-751.mp4

It's an issue with the System Launcher in versions after RELEASE-5.39.31.10324-11291001. They all come from the HyperOS beta for now, I can provide a simple fix in a temporary branch and wait to see if this issue persists in the official version

这个是系统桌面的问题，RELEASE-5.39.31.10324-11291001之后的版本会有这个问题，目前这些版本都来自beta版，我可以先在临时分支简单修复一下，等正式版看看这个问题是不是还存在

**Comment by parallelcc** [comment]
[abd2335_build](https://github.com/parallelcc/MiCTS/actions/runs/12322811459/artifacts/2319397052)

**Comment by kiber-io** [comment]
> [abd2335_build](https://github.com/parallelcc/MiCTS/actions/runs/12322811459/artifacts/2319397052)

Yes, everything worked fine. Thanks!

**Comment by rponeawa** [comment]
> [abd2335_build](https://github.com/parallelcc/MiCTS/actions/runs/12322811459/artifacts/2319397052)

谢谢，工作了！
