### ISSUE TITLE
Doesn't open 

### ISSUE THREAD

**Issue by Hydro3ia** [parallelcc/MiCTS#26]
**问题描述 / Describe the bug**
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**
![Screenshot_20241215-134421](https://github.com/user-attachments/assets/2986e151-02f4-47c5-99b8-0730c854970d)

**屏幕边缘是否闪了 / Did the screen edge flash?**
Yes

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
No

**设备型号 / Device model**
Sony Xperia 1 III

**系统版本 / OS version**
61.2.A.0.472A release-keys

**Android 版本 / Android version**
13

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed
[LSPosed_2024-12-15T13_45_26.442185.zip](https://github.com/user-attachments/files/18139055/LSPosed_2024-12-15T13_45_26.442185.zip)

**Comment by parallelcc** [comment]
![Screenshot_2024-12-15-13-59-25-611_bin mt plus](https://github.com/user-attachments/assets/eae8a7c2-2659-4a75-ab29-47085f2fe6dc)

`enableOmnient=false`代表Google的flag禁用了圈定即搜功能，需要参考README通过GMS-Flags修改flag
