### ISSUE TITLE
1.2 version still doesn't work

### ISSUE THREAD

**Issue by aprimasheva** [parallelcc/MiCTS#3]
Still doesn't work on latest version with gesture navbar. But work with button navbar.
OS: HyperOS UMRIDXM 1.0.9.0 Android 14
Device: Poco F5 (marble)

**Comment by parallelcc** [comment]
What is the System Launcher version? Please upload the logs inside lsposed, thx!

**Comment by parallelcc** [comment]
Currently, this module is not enabled for Poco Launcher. It might work if enabled, but I don't have the device to test. 

Try this apk by removing the .zip extension: [app-debug.apk.zip](https://github.com/user-attachments/files/17643049/app-debug.apk.zip)


If it still doesn't work, please upload the logs exported by the save button at the top of the log tab in lsposed.

**Comment by aprimasheva** [comment]
> Currently, this module is not enabled for Poco Launcher. It might work if enabled, but I don't have the device to test.
> 
> Try this apk by removing the .zip extension: [app-debug.apk.zip](https://github.com/user-attachments/files/17643049/app-debug.apk.zip)
> 
> If it still doesn't work, please upload the logs exported by the save button at the top of the log tab in lsposed.

Thank you. I'll try and let you know ASAP.

**Comment by aprimasheva** [comment]
> Currently, this module is not enabled for Poco Launcher. It might work if enabled, but I don't have the device to test.
> 
> Try this apk by removing the .zip extension: [app-debug.apk.zip](https://github.com/user-attachments/files/17643049/app-debug.apk.zip)
> 
> If it still doesn't work, please upload the logs exported by the save button at the top of the log tab in lsposed.

After uninstall latest release version and install the debug version above, it works normally with gesture navigation bar. Thank you for your assistance😁
