### ISSUE TITLE
Trojan detected in virustotal

### ISSUE THREAD

**Issue by Sevo9128** [parallelcc/MiCTS#30]
![Screenshot_20241226-153515](https://github.com/user-attachments/assets/150a97ad-5756-49f7-bb35-0a69c0d6f1c6)

When scanned in virustotal the scan returns a trojan, any explanation for such outcoming?

**Comment by parallelcc** [comment]
false positive

**Comment by parallelcc** [comment]
Fed back to ikarus and they replied: The false positive was removed and should not occur any more after our next database update.
