### ISSUE TITLE
Haptic Feedback/Vibration while triggering the app?

### ISSUE THREAD

**Issue by kratoz29** [parallelcc/MiCTS#31]
Just wondering if it is possible to have haptic feedback/vibration when I trigger micts?

Currently I use the navigation bar in the System Launcher (Lsposed) and it works like a charm, only that I don't get any feedback while triggering it that way. 

**设备型号 / Device model**

Poco F2 Pro (lmi)

**系统版本 / OS version**

MIUI 14 global 

**Android 版本 / Android version**

Android 12

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**

System Launcher RELEASE-4.39.9.6551-061 71028

**Comment by parallelcc** [comment]
Supported in [v2.2](https://github.com/parallelcc/MiCTS/releases/tag/v2.2)

**Comment by kratoz29** [comment]
> Supported in [v2.2](https://github.com/parallelcc/MiCTS/releases/tag/v2.2)

Thank you very much for considering my recommendation, it definitely improves the experience and I now find it truly native in MIUI like I once did when trying an AOSP custom ROM.
