### ISSUE TITLE
不完全正常工作

### ISSUE THREAD

**Issue by ERRORawa** [parallelcc/MiCTS#33]
**问题描述 / Describe the bug**
长按小白条经常不出现圈定即搜
> 确认已设置Google为默认助理应用，并且没有使用其他限制后台启动的模块或软件
> Make sure you have set Google as the default assistant app, and no other modules or apps that restrict background startup are being used

**MiCTS设置页面截图 / Screenshot of the MiCTS settings**
![Screenshot_2024-12-29-14-28-03-579_com parallelc micts](https://github.com/user-attachments/assets/58de56cc-2ffd-4876-af74-fb7676a6403b)

**屏幕边缘是否闪了 / Did the screen edge flash?**
否

**是否可以通过其他方式触发 / Can it be triggered by other methods?**
VIS可以正常工作，并且触发无延迟

**设备型号 / Device model**
Redmi K40

**系统版本 / OS version**
OS2.0.3.0 VMCCNXM

**Android 版本 / Android version**
15

**桌面版本（小米设备） / Launcher version (Xiaomi devices)**
RELEASE-5.39.31.10438-12162101

**LSPosed日志 / LSPosed logs**
> 上传通过LSPosed log页面最上面的保存按钮导出的zip文件
> Upload the zip file exported by the save button at the top of the log tab in LSPosed
[LSPosed_2024-12-29T14_31_34.193441.zip](https://github.com/user-attachments/files/18268726/LSPosed_2024-12-29T14_31_34.193441.zip)

**Comment by parallelcc** [comment]
[v2.2](https://github.com/parallelcc/MiCTS/releases/tag/v2.2) 已修复
