### ISSUE TITLE
Gesture mode not triggering 

### ISSUE THREAD

**Issue by UltimateWorm** [parallelcc/MiCTS#5]
https://github.com/user-attachments/assets/866feb30-ed13-4154-ac65-50b25da40e38

In gesture mode not triggering

**Comment by parallelcc** [comment]
Please provide your launcher version and lsposed logs

**Comment by UltimateWorm** [comment]
> Please provide your launcher version and lsposed logs

![Screenshot_2024-11-09-16-05-56-598_com miui home](https://github.com/user-attachments/assets/91833fa9-0c14-4b6f-a00b-ce4d299cfba3)

![Screenshot_2024-11-09-16-05-43-729_com miui securitycenter](https://github.com/user-attachments/assets/11eeddb8-0c56-4add-ac98-71fcdb5d10fa)

My device is Poco f3 gt official it comes with poco launcher but i am using system launcher mod

**Comment by UltimateWorm** [comment]
![LSPosed_2024-11-09T16_11_04.847277.zip](https://github.com/user-attachments/files/17686843/LSPosed_2024-11-09T16_11_04.847277.zip)

Module logs

![LSPosed_2024-11-verbos.zip](https://github.com/user-attachments/files/17686845/LSPosed_2024-11-verbos.zip)

Verbos logs

**Comment by parallelcc** [comment]
Try long-pressing the System launcher in the module scope of LSPosed, select 'Re-optimize,' and then select 'Force stop'

I noticed that you're using [HyperOS-Launcher](https://github.com/Mods-Center/HyperOS-Launcher), 'Circle to Search' is already supported in its 3.3 version

**Comment by UltimateWorm** [comment]
https://github.com/user-attachments/assets/c5e8ee31-396f-4d26-8ef8-5c7826701e58

> Try long-pressing the System launcher in the module scope of LSPosed, select 'Re-optimize,' and then select 'Force stop'
> 
> I noticed that you're using [HyperOS-Launcher](https://github.com/Mods-Center/HyperOS-Launcher), 'Circle to Search' is already supported in its 3.3 version


Still not worked, yes i am using latest version mod of hyper os launcher

**Comment by parallelcc** [comment]
Since this is a modified version of the System launcher, it seems the module isn't working due to its modifications, and there won't be dedicated support for it

The log shows you're using HyperOS-Launcher version 3.2, which is not the latest. You could try using version 3.3, which includes its own 'Circle to Search' feature

**Comment by UltimateWorm** [comment]
> Since this is a modified version of the System launcher, it seems the module isn't working due to its modifications, and there won't be dedicated support for it
> 
> The log shows you're using HyperOS-Launcher version 3.2, which is not the latest. You could try using version 3.3, which includes its own 'Circle to Search' feature


I tried it with poco launcher working perfectly in both gesture and buttons mode

But in hyperos launcher mod it is not working in gesture mode

![Screenshot_2024-11-09-20-10-28-169_com.google.android.documentsui.jpg](https://github.com/user-attachments/assets/12feeabf-7967-4fae-bae4-06e29e0d8bf5)

![Screenshot_2024-11-09-20-09-53-471_f.bdze.tth.gpirxu.jpg](https://github.com/user-attachments/assets/6806550f-6f28-4b02-a8c1-4e33bf1922bb)

Also dont know why it showing as version 3.2 but i have flashed 3.3, I even tried clean install by uninstalling old module first then installing new 3.3 but it just shows 3.2 🤔

**Comment by parallelcc** [comment]
Well, if you flashed 3.3, then circle to search should work without this module, if not, feedback to hyperos launcher mod

**Comment by UltimateWorm** [comment]
> Well, if you flashed 3.3, then circle to search should work without this module, if not, feedback to hyperos launcher mod

Yes i posted an issue on launcher mod page
Btw thankyou for helping me in this 🫱🏼‍🫲🏾

**Comment by parallelcc** [comment]
In future versions, this module will provide a trigger entry, allowing you to use other apps, such as Xposed Edge, to customize the trigger regardless of the launcher you are using

**Comment by UltimateWorm** [comment]
> In future versions, this module will provide a trigger entry, allowing you to use other apps, such as Xposed Edge, to customize the trigger regardless of the launcher you are using
> 
> 

Interesting 😁 eagerly waiting for the future updates. I hope it will arrive soon

**Comment by parallelcc** [comment]
micts will reuse the circle to search function when it detects that the system launcher already support it, but the function of the hyperos launcher mod only seems to support a14, I think that's the reason why it doesn't work

**Comment by UltimateWorm** [comment]
> micts will reuse the circle to search function when it detects that the system launcher already support it, but the function of the hyperos launcher mod only seems to support a14, I think that's the reason why it doesn't work

Yeah maybe, but for me it is not working only in gesture mode but in buttons mode it is working perfectly and in default poco launcher it is working in both gesture and buttons mode, i think the problem is in the hyperos launcher mod

**Comment by parallelcc** [comment]
Well, while this is indeed an issue with the hyperos launcher mod, I can try tweaking a bit to see if can get it to work

Try this apk by removing the .zip extension:  [app-debug.apk.zip](https://github.com/user-attachments/files/17690731/app-debug.apk.zip)

**Comment by UltimateWorm** [comment]
> Well, while this is indeed an issue with the hyperos launcher mod, I can try tweaking a bit to see if can get it to work
> 
> Try this apk by removing the .zip extension:  [app-debug.apk.zip](https://github.com/user-attachments/files/17690731/app-debug.apk.zip)
> 

Updated the old module with this one and it worked 😮

**Comment by parallelcc** [comment]
Just release [1.4](https://github.com/parallelcc/MiCTS/releases/tag/v1.4)

**Comment by UltimateWorm** [comment]
> Just release [1.4](https://github.com/parallelcc/MiCTS/releases/tag/v1.4)

So it is the same apk u gave me above ? Or different

**Comment by parallelcc** [comment]
> > Just release [1.4](https://github.com/parallelcc/MiCTS/releases/tag/v1.4)
> 
> So it is the same apk u gave me above ? Or different

It's the release version. What I gave you above was the debug version. The functions are the same, but the version numbers are different and only the release version can be upgraded in the future without uninstalling

**Comment by UltimateWorm** [comment]
> > > Just release [1.4](https://github.com/parallelcc/MiCTS/releases/tag/v1.4)
> > 
> > So it is the same apk u gave me above ? Or different
> 
> It's the release version. What I gave you above was the debug version. The functions are the same, but the version numbers are different and only the release version can be upgraded in the future without uninstalling

Ohkay thankyou for info..
I upgraded with the latest release, everything is working perfectly 👍🏻 thankyou for listening to my feedback 🫱🏼‍🫲🏾
