### ISSUE TITLE
请求适配小米平板

### ISSUE THREAD

**Issue by KOWX712** [parallelcc/MiCTS#6]
型号：Xiaomi Pad 6 Pro
系统：澎湃1.0 安卓14
状况：目前导航键可以触发，但是手势条不能。
附件：视频

https://github.com/user-attachments/assets/614fda36-11f6-48ea-9ea0-858b8dacc9f0

感谢

**Comment by parallelcc** [comment]
提供一下系统桌面的版本和lsposed日志

**Comment by KOWX712** [comment]
桌面版本：
![Screenshot_2024-11-10-02-59-57-884_com miui securitycenter](https://github.com/user-attachments/assets/38d302b6-8bd6-4622-a333-ffce9a27d874)
[System launcher_RELEASE-4.40.0.7219-05081617.zip](https://github.com/user-attachments/files/17689063/System.launcher_RELEASE-4.40.0.7219-05081617.zip)

LSPosed 日志：
[LSPosed_2024-11-10T03_02_38.386679.zip](https://github.com/user-attachments/files/17689064/LSPosed_2024-11-10T03_02_38.386679.zip)

**Comment by parallelcc** [comment]
从视频看，手势条好像不可点击了，左右滑动手势条切换应用正常吗

**Comment by KOWX712** [comment]
应该是可以的，晚点用miui extra模块再录个视频，那个模块是可以识别到手势条按压的。

**Comment by KOWX712** [comment]
此视频只是用来可视化导航条的按压/滑动，测试MiCTS时已关闭此模块，应该不存在模块冲突问题
附件：视频

https://github.com/user-attachments/assets/bae1bac3-ea96-49a9-9b1d-40de23b76df3

感谢

**Comment by parallelcc** [comment]
目前看日志都正常，但系统桌面没有进入触发逻辑，手里没有平板设备，不是很好排查

之后的版本会提供一个触发入口，到时候可以通过其他软件，比如Xposed Edge自定义触发方式，那样就不依赖系统桌面了

**Comment by parallelcc** [comment]
> 目前看日志都正常，但系统桌面没有进入触发逻辑，手里没有平板设备，不是很好排查
> 
> 之后的版本会提供一个触发入口，到时候可以通过其他软件，比如Xposed Edge自定义触发方式，那样就不依赖系统桌面了

初步实现了一版，可以尝试一下，启动软件就可以触发 [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)

**Comment by KOWX712** [comment]
配置xposed edge成功唤起，十分感谢。

https://github.com/user-attachments/assets/b75a1403-c311-4435-9936-8e0f5a096017
