### ISSUE TITLE
感谢大佬，想知道有啥类似快捷方式可以调用吗

### ISSUE THREAD

**Issue by gicannu** [parallelcc/MiCTS#7]
如题如题，底部识别有点难按，想用类似悬浮球之类的软件来调用

**Comment by parallelcc** [comment]
之后的版本会提供一个触发入口，到时候可以通过其他软件，比如Xposed Edge自定义触发方式

**Comment by gicannu** [comment]
好咧，期待，太好用了，颠覆小米

**Comment by parallelcc** [comment]
初步实现了一版，可以尝试一下，启动软件就可以触发 [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)
