### ISSUE TITLE
Bug in the circule to search

### ISSUE THREAD

**Issue by carlospinheirot** [parallelcc/MiCTS#8]
Sometimes, some areas the gesture to circle doesn't work

**Comment by carlospinheirot** [comment]
The bug occurs in the dock region. Even within the apps, this region does not work.

**Comment by carlospinheirot** [comment]
The bug occurs in the dock region. Even within the apps, this region does not work.

**Comment by carlospinheirot** [comment]
The bug occurs in the dock region. Even within the apps, this region does not work.

**Comment by parallelcc** [comment]
This module is only responsible for triggering Google's circle to search function and cannot handle any issues that may arise after triggering
