### ISSUE TITLE
Which android version supported ?

### ISSUE THREAD

**Issue by elswerky** [parallelcc/MiCTS#9]
Bro 
Can you please explain if it can work on Android 13 or just android 14 and above ??
 And also explain it in thread

**Comment by parallelcc** [comment]
It's currently known to work on Android 12~15. It may also work on older versions, but need test and feedback

Not sure which thread do you mean

**Comment by elswerky** [comment]
> It's currently known to work on Android 12~15. It may also work on older versions
> 
> Not sure which thread do you mean

Great I thought it work only in Android 14 and above 
I mean topic here in GitHub , write a note explain which android version it supports 

Also bro 
Can we get similar Xposed module to work on Samsung devices especially android 13 where it doesn't work 

Also if there is a telegram group or channel for it mention it in notes here

**Comment by parallelcc** [comment]
I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released

**Comment by elswerky** [comment]
> I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released

Bro
In Samsung Android 14 , they add an option in display settings to enable circle to search 
So such option not present on Android 13 , so I hope you can make it work work in Samsung oneui 5.1 android 13 
Would be great as Samsung software is Abit different than Xiaomi one

**Comment by parallelcc** [comment]
> I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released

Completed an initial version, give it a try  [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)

Launching the app will trigger so you can customize the trigger with other apps/modules like xposed edge

**Comment by elswerky** [comment]
> > I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released
> 
> Completed an initial version, give it a try [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)
> 
> Launching the app will trigger so you can customize the trigger with other apps/modules like xposed edge

I tested it bro
First app Suze is too small compared to previous build only 26 lb instead of 600 lb
Second on samsing note 10 lite oneui 5.1 Android 13 
Long press on navigation handle doesn't trigger any thing 
Plus app icon doesn't open

**Comment by parallelcc** [comment]
> > > I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released
> > 
> > 
> > Completed an initial version, give it a try [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)
> > Launching the app will trigger so you can customize the trigger with other apps/modules like xposed edge
> 
> I tested it bro First app Soze is too small compared to previous build only 26 kb instead of 600 lb Second on samsung note 10 lite oneui 5.1 Android 13 Long press on navigation handle doesn't trigger any thing Plus app icon doesn't open

try using [circle-to-search-spoofer](https://github.com/fillwithjoy1/circle-to-search-spoofer), see if can open the app

**Comment by elswerky** [comment]
> > > > I'm implementing a trigger entry to make the function independent of specific devices and launchers, and may even work without Xposed. will rewrite the doc before it's released
> > > 
> > > 
> > > Completed an initial version, give it a try [57ac3c5_build](https://github.com/parallelcc/MiCTS/actions/runs/11790950321/artifacts/2174453618)
> > > Launching the app will trigger so you can customize the trigger with other apps/modules like xposed edge
> > 

> > 
> > I tested it bro First app Soze is too small compared to previous build only 26 kb instead of 600 lb Second on samsung note 10 lite oneui 5.1 Android 13 Long press on navigation handle doesn't trigger any thing Plus app icon doesn't open
> 
> try using [circle-to-search-spoofer](https://github.com/fillwithjoy1/circle-to-search-spoofer), see if can open the app



now your 26 kb app open as if trigger navigation handle 

worked with the pixelify like module 
first installled small 2 kb module didn;t work ,,then installed pixelify like ( so both modules from link flashed but i think pixelify like is the one make your app open )

is ther a way to trigger the handle to open cts ?? or integrating it as you said

but anyway short long answer 
now your app open and trigger cts

**Comment by elswerky** [comment]
![Screenshot_20241112_114157_One UI Home](https://github.com/user-attachments/assets/85d98590-1829-481a-a3d7-f67634413f36)

I integrated your app tonshortcut panel of xposed edge app
And now it works better way on any page 

Thanks for notifying about xposed edge 
Also if you have better way or better interruption tell me 
Thank you for your support

**Comment by elswerky** [comment]
But the circle don't appear 
So can't circle anything to search it

**Comment by elswerky** [comment]
![Uploading Screenshot_20241112_115401_Google.jpg…]()

**Comment by parallelcc** [comment]
if you want to simulate the long press the handle to trigger, you can go to 'Gestures - Bottom center - Long press' in xposed edge, then select 'App' and choose MiCTS

**Comment by elswerky** [comment]
![Screenshot_20241112_115401_Google](https://github.com/user-attachments/assets/9c61560b-04c0-4179-9400-56d5ab3c17af)

**Comment by elswerky** [comment]
> if you want to simulate the long press the handle to trigger, you can go to 'Gestures - Bottom center - Long press' in xposed edge, then select 'App' and choose MiCTS

I added it same way 
I trigger this shortcut menu in screenshot by swiping up right lower edge ( old back gesture ) and from shortcut mrnu I choose it like in screenshot 

Thank you 
 This si On Android 13 , Samsung Note 10 lite

**Comment by elswerky** [comment]
Worked with the 4 mb lspsoed module like pixelify

**Comment by elswerky** [comment]
> if you want to simulate the long press the handle to trigger, you can go to 'Gestures - Bottom center - Long press' in xposed edge, then select 'App' and choose MiCTS


Yeah bro right , with this gesture it is similar like in officially supported devices 
You are magniglficant 
Before they tied me only work on android 14 and later

**Comment by parallelcc** [comment]
Implemented device spoof in xposed function, now don't need other spoof modules [b5a8bc0_build](https://github.com/parallelcc/MiCTS/actions/runs/11802433335/artifacts/2177665850)

**Comment by elswerky** [comment]
> Implemented device spoof in xposed function, now don't need other spoof modules [b5a8bc0_build](https://github.com/parallelcc/MiCTS/actions/runs/11802433335/artifacts/2177665850)


Not working bro on my side 
Tested on two Samsung devices running android 12 and 13 
Still needs the circle to search pixelify like Xposed module 

Also cleared data of google app

App when I click on it doesn't trigger CTS 

Plz if you have telegram can you send me messages there at @elswerky
For fast easy  chatting

**Comment by parallelcc** [comment]
> > Implemented device spoof in xposed function, now don't need other spoof modules [b5a8bc0_build](https://github.com/parallelcc/MiCTS/actions/runs/11802433335/artifacts/2177665850)
> 
> Not working on my side Tested on two Samsung devices running android 12 and 13 Still needs the circle to search pixelify like Xposed module
> 
> Also cleared data of google app
> 
> App when I click on it doesn't trigger CTS
> 
> Plz if you have telegram can you send me messages there at @elswerky For fast easy chatting

Did you activate micts and select Google in lsposed

**Comment by elswerky** [comment]
> Did you activate micts and select Google in lsposed

Yeah right 
Now it is working 
It is just because I updated app , didn't notice to select google and wasn't selected by default when updated

Now it works ,thanks for the hint 
And the most important thanks for the just 40 kb module that integrate such important features

**Comment by parallelcc** [comment]
[2.0](https://github.com/parallelcc/MiCTS/releases/tag/v2.0) released

**Comment by Clanceeinfinity** [comment]
works on my tab s7 with android 14, doesn't work for me on my duo with android 15
